version: '3.1'

services:

  server:
    build: .
    container_name: "spring-boot-container"
    image: "spring-boot-image"
    # restart: always
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy

  # https://hub.docker.com/_/mysql
  db:
    image: mysql:latest
    container_name: "mysql-db"
    # restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306
    # https://stackoverflow.com/questions/42567475/docker-compose-check-if-mysql-connection-is-ready
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10